<a href="https://colab.research.google.com/github/phiang2548tha-alt/chat-mini-project/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_ch02_059.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Read CSV

In [ ]:
import pandas as pd
df_csv = pd.read_csv('/content/drive/MyDrive/2569-1DS 059/ข้อมูล.csv',encoding='utf-8')
# df_csv.head()
print(df_csv.head())

  id,name,score
0    1,สมชาย,85
1     2,สุดา,92
2   3,อนันต์,78
3     4,มาลี,88
4    5,กิตติ,95

#Export CSV

In [ ]:
df_csv.to_csv('/content/drive/MyDrive/2569-1DS 059/ข้อมูล.csv',index=False,encoding='utf-8')

In [ ]:
df_csv.to_csv('/content/drive/MyDrive/2569-1DS 059/ข้อมูล.csv',index=False,encoding='utf-8-sig')

In [ ]:
print(df_csv.head())

  id,name,score
0    1,สมชาย,85
1     2,สุดา,92
2   3,อนันต์,78
3     4,มาลี,88
4    5,กิตติ,95

#จัดการข้อมูลสูญหาย

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/2569-1DS 059/example_missing_data.csv')
print(df3)

   id   name  score
0   1  สมชาย   85.0
1   2   สุดา    NaN
2   3    NaN   78.0
3   4   มาลี   88.0
4   5  กิตติ   95.0
5   6   อารี    NaN
6   7    NaN   67.0
7   8  ปวีณา   91.0
8   9    ธนา    NaN
9  10    NaN   73.0

In [ ]:
missing_df3 = df3.isnull().sum()
print(missing_df3)

id       0
name     3
score    3
dtype: int64

In [ ]:
df3['score'].fillna(df3['score'].mean(),inplace=True)
missing_df3 = df3.isnull().sum()
print(missing_df3)

id       0
name     3
score    0
dtype: int64

/tmp/ipykernel_623/2273399899.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['score'].fillna(df3['score'].mean(),inplace=True)

In [ ]:
df_clean = df3.dropna()
df4 = df_clean.isnull().sum()
print(df4)

id       0
name     0
score    0
dtype: int64

In [ ]:
df5 = pd.read_csv('/content/drive/MyDrive/2569-1DS 059/data_type_conversion_lab.csv')

In [ ]:
df5.dtypes

StudentID           int64
Name               object
Gender             object
EnrollmentDate     object
BirthDate          object
Department         object
Grade             float64
Status             object
dtype: object

In [ ]:
df5['New_date'] = pd.to_datetime(df5['EnrollmentDate'])
df5.head()

,StudentID,Name,Gender,EnrollmentDate,BirthDate,Department,Grade,Status,New_date
0,1001,Anan,Male,2023-05-15,2004-01-20,Computer Science,3.45,Active,2023-05-15
1,1002,Suda,Female,2022-06-01,2003-08-12,Business,3.12,Active,2022-06-01
2,1003,Krit,Male,2021-08-20,2002-11-05,Engineering,2.98,Inactive,2021-08-20
3,1004,Nok,Female,2023-01-10,2004-04-18,Computer Science,3.78,Active,2023-01-10
4,1005,Somchai,Male,2022-09-25,2003-02-28,Engineering,2.75,Graduated,2022-09-25

In [ ]:
df5['New_Gender'] = df5['Gender'].astype('category')
df5.head()

,StudentID,Name,Gender,EnrollmentDate,BirthDate,Department,Grade,Status,New_date,New_Gender
0,1001,Anan,Male,2023-05-15,2004-01-20,Computer Science,3.45,Active,2023-05-15,Male
1,1002,Suda,Female,2022-06-01,2003-08-12,Business,3.12,Active,2022-06-01,Female
2,1003,Krit,Male,2021-08-20,2002-11-05,Engineering,2.98,Inactive,2021-08-20,Male
3,1004,Nok,Female,2023-01-10,2004-04-18,Computer Science,3.78,Active,2023-01-10,Female
4,1005,Somchai,Male,2022-09-25,2003-02-28,Engineering,2.75,Graduated,2022-09-25,Male

In [ ]:
df5.dtypes

StudentID                  int64
Name                      object
Gender                    object
EnrollmentDate            object
BirthDate                 object
Department                object
Grade                    float64
Status                    object
New_date          datetime64[ns]
New_Gender              category
dtype: object

In [ ]:
fil_df5 = df5[df5['Grade'] > 3.00]
fil_df5.head(3)

,StudentID,Name,Gender,EnrollmentDate,BirthDate,Department,Grade,Status,New_date,New_Gender
0,1001,Anan,Male,2023-05-15,2004-01-20,Computer Science,3.45,Active,2023-05-15,Male
1,1002,Suda,Female,2022-06-01,2003-08-12,Business,3.12,Active,2022-06-01,Female
3,1004,Nok,Female,2023-01-10,2004-04-18,Computer Science,3.78,Active,2023-01-10,Female

In [ ]:
fil2_df5 = df5[(df5['Department'] =='Computer Science') & (df5['Grade'] > 3.00)]
fil2_df5.head(3)

,StudentID,Name,Gender,EnrollmentDate,BirthDate,Department,Grade,Status,New_date,New_Gender
0,1001,Anan,Male,2023-05-15,2004-01-20,Computer Science,3.45,Active,2023-05-15,Male
3,1004,Nok,Female,2023-01-10,2004-04-18,Computer Science,3.78,Active,2023-01-10,Female
6,1007,Ploy,Female,2023-03-03,2004-09-15,Computer Science,3.91,Active,2023-03-03,Female

In [ ]:
gr = df5.groupby('Department')['Grade'].mean()
gr

Department
Business            3.110000
Computer Science    3.635000
Engineering         2.976667
Name: Grade, dtype: float64

In [ ]:
gr = df5.groupby('Department')['Grade'].agg(['mean','max','min'])
gr

                      mean   max   min
Department
Business          3.110000  3.56  2.65
Computer Science  3.635000  3.91  3.40
Engineering       2.976667  3.20  2.75